// GET DATA actionTypes

export const DATA_GET_REQUEST = 'DATA_GET_REQUEST'
export const DATA_GET_SUCCESS = 'DATA_GET_SUCCESS'
export const DATA_GET_FAILURE = 'DATA_GET_FAILURE'

export const CART_ADD_REQUEST = 'CART_ADD_REQUEST'
export const CART_ADD_SUCCESS = 'CART_ADD_SUCCESS'
export const CART_ADD_FAILURE = 'CART_ADD_FAILURE'


// category export

export const CATEGORY_UPDATE = 'CATEGORY_UPDATE'