// GET DATA actionTypes

export const DATA_GET_REQUEST = 'DATA_GET_REQUEST'
export const DATA_GET_SUCCESS = 'DATA_GET_SUCCESS'
export const DATA_GET_FAILURE = 'DATA_GET_FAILURE'

// GET CART DATA actionTypes
export const CART_GET_REQUEST = 'CART_GET_REQUEST';
export const CART_GET_SUCCESS = 'CART_GET_SUCCESS';
export const CART_GET_FAILURE = 'CART_GET_FAILURE';

// GET WISHLIST DATA actionTypes
export const WISHLIST_GET_REQUEST = 'WISHLIST_GET_REQUEST';
export const WISHLIST_GET_SUCCESS = 'WISHLIST_GET_SUCCESS';
export const WISHLIST_GET_FAILURE = 'WISHLIST_GET_FAILURE';
